  angular
      .module('app',[
          'ngMaterial',
          'ui.router',
					'restangular',
					'app.user',
					'app.logs',
					'app.pages'
      ])
angular
	.module('app.user',[])
angular
	.module('app.logs',[])
angular
	.module('app.pages',[])
